#+TITLE: Rust Challenges
#+DESCRIPTION: Các Challenges hàng tuần - có giải thưởng.
#+AUTHOR: Dang Quang Vu
#+EMAIL: eamondang@gmail.com

#+begin_quote
+ Trò chơi giải thuật toán với giải thưởng được tổ chức hàng tuần trên [[https://discord.gg/MwQSTmuV5w][Rustaceans Communication]]
+ Trao giải trực tiếp qua livestream trên VBI vào cuối tuần trên [[https://www.youtube.com/@VBIBlockchainAcademy][VBI Channel]]
+ Hình thức sẽ chọn ra bạn có điểm benchmark cao nhất trong các solution.
+ Cách thức nộp bài sẽ nộp dưới dạng merge git vào branch tương ứng.
#+end_quote

* Challenges :TOC:
- [[#challenge-2][Challenge 2]]
  - [[#đề-bài][Đề bài]]
- [[#challenge-1---strobogrammatic-find---week-1][Challenge 1 - Strobogrammatic Find - Week 1]]
  - [[#đề-bài-1][Đề bài]]
  - [[#winner][Winner]]

* Challenge 2
** Đề bài
+ Cho một array các string, và max_width.
+ Nhiệm vụ là định dạng văn bản làm sao để mỗi dòng có đúng max_width ký tự và được *căn giữa.*

+ input
#+begin_src rustic
words = ["TowerBFT", "allows", "the", "Solana", "network", "to", "process", "thousands", "of", "transactions", "per", "second", "and", "is", "easily", "scalable", "to", "meet", "the", "growing", "demands", "of", "the", "blockchain", "network."]

max_width = 16
#+end_src

+ output
#+begin_src rustic
[
  "TowerBFT  allows",
  "the       Solana",
  "network       to",
  "process         ",
  "thousands     of",
  "transactions per",
  "second   and  is",
  "easily  scalable",
  "to    meet   the",
  "growing  demands",
  "of           the",
  "blockchain      ",
  "network.        ",
]
#+end_src

+ Notes:
  + Khoảng cách ' ' nên được phân bố đều nhất có thể.
  + Đối với dòng cuối thì sẽ không canh giữa.

#+begin_quote
+ Độ dài của mỗi từ được đảm bảo lớn hơn 0 và không vượt quá max_width.
+ Mảng nhập vào words chứa ít nhất một từ.
+ 1 <= max_width <= 100
+ 1 <= len(words[i]) <= max_width
+ 1 <= len(words) <= 300
#+end_quote

+ more examples
#+begin_src rust
words = ["This", "is", "a", "simple", "test", "case", "for", "center", "justification."]
max_width = 14
#+end_src

+ output
#+begin_src rust
[
  "This    is   a",
  "simple    test",
  "case       for",
  "center        ",
  "justification.",
]
#+end_src

#+begin_src rustic
let words = vec!["The", " Gulf", " Stream", " is", " driven", " by", " a", " combination", " of", " wind", " patterns,", " temperature", " differences,", " and", " the", " Earth's", " rotation.",];
let max_width = 13;
#+end_src
#+begin_src rust
[
    "The      Gulf",
    " Stream    is",
    " driven    by",
    " a           ",
    " combination ",
    " of      wind",
    " patterns,   ",
    " temperature ",
    " differences,",
    " and      the",
    " Earth's     ",
    " rotation.   ",
]
#+end_src

* Challenge 1 - Strobogrammatic Find - Week 1
** Đề bài
+ Cho hai chuỗi số low và high, hãy tìm tất cả các số strobogrammatic nằm trong khoảng từ low đến high.
#+begin_quote
+ Một số được gọi là *strobogrammatic* nếu nó có thể được quay 180 độ và trông giống như chính nó. Các chữ số strobogrammatic là 0, 1, 6, 8, 9.
+ Lưu ý rằng các số không thể có các chữ số dẫn đầu bằng 0, ví dụ như "00".
#+end_quote

Ví dụ:
+ Input: low = 50, high = 100
+ Output: 3
+ Giải thích: Các số strobogrammatic từ 50 đến 100 là ["69", "88", "96"], do đó kết quả trả về là 3.

+ 10 <= low <= 10000
+ 10 <= high <= 10000
+ low < high

Một số gợi ý:
+ Sử dụng đệ quy để tạo ra tất cả các số strobogrammatic có độ dài n.
+ Kiểm tra xem mỗi số có nằm trong khoảng từ low đến high không và đếm số lượng số thỏa mãn yêu cầu đó.

[[./src/week1/mod.rs][Week1 Strobogrammatic Numbers]]

** Winner
+ phuctabahoang#4250
